### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by michael-jonas**
Fix for https://github.com/michael-jonas/Door_Locker/issues. Thanks to Laurier for noticing the problem.

### CODE REVIEW

**Comment by LaurierMantel** [comment]
I'm going to have to give it the 🔴 on this.  Not very descriptive, hard for new people to come and understand the project

**Comment by LaurierMantel** [comment]
Maybe add a WIP label for now and we can come back to it

**Comment by LaurierMantel** [comment]
Also this closes #1

**Comment by LaurierMantel** [comment]
would love to hear input from @rishigoel, @ndey96, @clvcooke

**Comment by michael-jonas** [comment]
Any particular headings you'd like to see?

**Comment by michael-jonas** [comment]
Closing this. Was fixed.

**Comment by LaurierMantel** [comment]
:+1: great work today everybody

**Pull request closed without merging**
